module('lively.bindings.FRPTranslator').requires('ometa.lively').toRun(function() {
FRPTranslator=objectThatDelegatesTo(OMeta,{
"combinator":function(){var $elf=this,_fromIdx=this.input.idx;return (function(){switch(this._apply('anything')){case "durationE":return "durationE";case "collectE":return "collectE";case "mergeE":return "mergeE";case "delayE":return "delayE";case "timerE":return "timerE";default: throw fail}}).call(this)},
"oTrans":function(){var $elf=this,_fromIdx=this.input.idx,tree;return (function(){tree=this._apply("anything");return BSOMetaJSTranslator.match(tree,"trans")}).call(this)},
"start":function(){var $elf=this,_fromIdx=this.input.idx,t;return (function(){this._apply("empty");(function (){(this["id"]=(0));(this["dependents"]=[]);(this["hasSubExpression"]=false);(this["triggerStack"]=[]);(this["result"]=new StringBuffer())}).bind(this)();t=this._apply("trans");return (function (){if(this["hasSubExpression"]){var result="(function () {var strm = new lively.bindings.FRPCore.EventStream();";(result=(result + this["result"].contents()));return (((result + "return strm.finalize([") + this["dependents"].join(", ")) + "])})();")}else{return t["refString"]}}).bind(this)()}).call(this)},
"trans":function(){var $elf=this,_fromIdx=this.input.idx,t,ans;return (function(){this._form((function(){return (function(){t=this._apply("anything");return ans=this._applyWithArgs("apply",t)}).call(this)}));return ans}).call(this)},
"curlyTrans":function(){var $elf=this,_fromIdx=this.input.idx,r,rs;return this._or((function(){return (function(){this._form((function(){return (function(){this._applyWithArgs("exactly","begin");return r=this._apply("curlyTrans")}).call(this)}));return r}).call(this)}),(function(){return (function(){this._form((function(){return (function(){this._applyWithArgs("exactly","begin");return rs=this._many((function(){return this._apply("trans")}))}).call(this)}));return (("{" + rs.join(";")) + "}")}).call(this)}),(function(){return (function(){r=this._apply("trans");return (("{" + r) + "}")}).call(this)}))},
"fby":function(){var $elf=this,_fromIdx=this.input.idx,trigger,init,body;return (function(){trigger=this._apply("trans");this._apply("empty");this["triggerStack"].push(trigger);init=this._apply("oTrans");body=this._apply("trans");return (function (){this["triggerStack"].pop();var isStream=(body["isStream"] || (trigger && trigger["isStream"]));if(isStream){var id=this.nextId();var strmDef=this.makeFby(init,[body]);var deps=body["dependencies"].clone().concat((trigger?trigger["dependencies"]:[]));this.addSubExpression(id,strmDef,deps);return ({"refString": this.ref(id),"dependencies": deps,"isStream": true})}else{return ({"refString": Strings.format("(%s)",body["refString"]),"dependencies": [],"isStream": false})}}).bind(this)()}).call(this)},
"binop":function(){var $elf=this,_fromIdx=this.input.idx,op,ll,rr;return (function(){op=this._apply("anything");ll=this._apply("trans");rr=this._apply("trans");return (function (){var isStream=(ll["isStream"] || rr["isStream"]);if(isStream){var id=this.nextId();var strmDef=this.makeBinop([ll,rr],op);var deps=ll["dependencies"].clone().concat(rr["dependencies"]);this.addSubExpression(id,strmDef,deps);return ({"refString": this.ref(id),"dependencies": deps,"isStream": true})}else{return ({"refString": Strings.format("(%s %s %s)",ll["refString"],op,rr["refString"]),"dependencies": [],"isStream": false})}}).bind(this)()}).call(this)},
"unop":function(){var $elf=this,_fromIdx=this.input.idx,op,ll;return (function(){op=this._apply("anything");ll=this._apply("trans");return (function (){var isStream=ll["isStream"];if(isStream){var id=this.nextId();var strmDef=this.makeUnop([ll],op);var deps=ll["dependencies"].clone();this.addSubExpression(id,strmDef,deps);return ({"refString": this.ref(id),"dependencies": deps,"isStream": true})}else{return ({"refString": Strings.format("(%s%s)",op,ll["refString"]),"dependencies": [],"isStream": false})}}).bind(this)()}).call(this)},
"func":function(){var $elf=this,_fromIdx=this.input.idx,args,body;return (function(){args=this._apply("anything");body=this._apply("curlyTrans");return [(((("(function (" + args.join(",")) + ")") + body) + ")"),false]}).call(this)},
"call":function(){var $elf=this,_fromIdx=this.input.idx,comb,ll,rr,f,args;return this._or((function(){return (function(){this._form((function(){return (function(){this._applyWithArgs("exactly","get");return comb=this._apply("combinator")}).call(this)}));ll=this._apply("trans");rr=this._apply("trans");return (function (){var id=this.nextId();var strmDef=this.makeCombinator(comb,[ll,rr]);var deps=ll["dependencies"].clone().concat(rr["dependencies"]);this.addSubExpression(id,strmDef,deps);return ({"refString": this.ref(id),"dependencies": deps,"isStream": true})}).bind(this)()}).call(this)}),(function(){return (function(){f=this._apply("oTrans");args=this._many((function(){return this._apply("trans")}));return (function (){var isStream=args.inject(false,(function (last,now){return (last || now["isStream"])}));if(isStream){var id=this.nextId();var strmDef=this.makeCall(f,args);var deps=args.inject([],(function (last,now){return last.concat(now["dependencies"])}));this.addSubExpression(id,strmDef,deps);return ({"refString": this.ref(id),"dependencies": deps,"isStream": true})}else{return ({"refString": Strings.format("%s(%s)",f,args.map((function (arg){return arg["refString"]})).join(", ")),"dependencies": deps,"isStream": false})}}).bind(this)()}).call(this)}))},
"get":function(){var $elf=this,_fromIdx=this.input.idx,n;return (function(){n=this._apply("anything");this._pred((n["constructor"] === String));return (function (){this["dependents"].push(this.ref(n));return ({"refString": this.ref(n),"dependencies": [n],"isStream": true})}).bind(this)()}).call(this)},
"getLast":function(){var $elf=this,_fromIdx=this.input.idx,n;return (function(){n=this._apply("anything");this._pred((n["constructor"] === String));return (function (){return ({"refString": (("this.getLast(\'" + n) + "\')"),"dependencies": [],"isStream": false})}).bind(this)()}).call(this)},
"number":function(){var $elf=this,_fromIdx=this.input.idx,n;return (function(){n=this._apply("anything");this._pred((n["constructor"] === Number));return (function (){return ({"refString": Objects.inspect(n),"dependencies": [],"isStream": false})}).bind(this)()}).call(this)},
"begin":function(){var $elf=this,_fromIdx=this.input.idx;return this._apply("trans")}})
});